// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wumsixpjlqlwiqmdhatv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bXNpeHBqbHFsd2lxbWRoYXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjM0OTcsImV4cCI6MjA2NjAzOTQ5N30.ReLnsOCL6LlssAh6woecH0aewyT135ZlIWUsE_yGIIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);